language: ruby
rvm:
  - 2.2.1
env:
  - DB=postgresql
script:
  - RAILS_ENV=test bundle exec rake db:migrate
  - bundle exec rspec
before_script:
  - psql -c 'create database bookstore_test' -U postgres